#!/usr/bin/env bun

import { $ } from "bun"
import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"
import solidPlugin from "@opentui/solid/bun-plugin"
import { createHash } from "crypto"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

import { Script } from "@opencode-ai/script"
import pkg from "../package.json"

// Build cache for incremental builds
const BUILD_CACHE_DIR = path.join(dir, ".build-cache")
await $`mkdir -p ${BUILD_CACHE_DIR}`

// Compute content hash for cache key
async function computeHash(content: string): Promise<string> {
  return createHash("sha256").update(content).digest("hex").slice(0, 16)
}

// Fetch and generate models.dev snapshot with caching
const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
const modelsCachePath = path.join(BUILD_CACHE_DIR, "models-snapshot-hash.txt")
let modelsHash: string | null = null

try {
  modelsHash = await Bun.file(modelsCachePath).text()
} catch {
  // Cache miss
}

const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())

const newModelsHash = await computeHash(modelsData)

if (modelsHash !== newModelsHash || !Bun.file(path.join(dir, "src/provider/models-snapshot.ts")).exists()) {
  await Bun.write(
    path.join(dir, "src/provider/models-snapshot.ts"),
    `// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData} as const\n`,
  )
  await Bun.write(modelsCachePath, newModelsHash)
  console.log("Generated models-snapshot.ts (cache miss)")
} else {
  console.log("Using cached models-snapshot.ts")
}

// Load migrations with caching
const migrationCachePath = path.join(BUILD_CACHE_DIR, "migrations-hash.txt")
let migrationsHash: string | null = null

try {
  migrationsHash = await Bun.file(migrationCachePath).text()
} catch {
  // Cache miss
}

const migrationDirs = (
  await fs.promises.readdir(path.join(dir, "migration"), {
    withFileTypes: true,
  })
)
  .filter((entry) => entry.isDirectory() && /^\d{4}\d{2}\d{2}\d{2}\d{2}\d{2}/.test(entry.name))
  .map((entry) => entry.name)
  .sort()

const migrations = await Promise.all(
  migrationDirs.map(async (name) => {
    const file = path.join(dir, "migration", name, "migration.sql")
    const sql = await Bun.file(file).text()
    const match = /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/.exec(name)
    const timestamp = match
      ? Date.UTC(
          Number(match[1]),
          Number(match[2]) - 1,
          Number(match[3]),
          Number(match[4]),
          Number(match[5]),
          Number(match[6]),
        )
      : 0
    return { sql, timestamp, name }
  }),
)

const migrationsHashContent = migrations.map((m) => `${m.name}:${m.sql.length}`).join("|")
const newMigrationsHash = await computeHash(migrationsHashContent)

if (migrationsHash !== newMigrationsHash) {
  await Bun.write(migrationCachePath, newMigrationsHash)
  console.log(`Loaded ${migrations.length} migrations (cache miss)`)
} else {
  console.log(`Using cached ${migrations.length} migrations`)
}

const singleFlag = process.argv.includes("--single")
const baselineFlag = process.argv.includes("--baseline")
const skipInstall = process.argv.includes("--skip-install")
const parallelFlag = process.argv.includes("--parallel") || !singleFlag

const allTargets: {
  os: string
  arch: "arm64" | "x64"
  abi?: "musl"
  avx2?: false
}[] = [
  {
    os: "linux",
    arch: "arm64",
  },
  {
    os: "linux",
    arch: "x64",
  },
  {
    os: "linux",
    arch: "x64",
    avx2: false,
  },
  {
    os: "linux",
    arch: "arm64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
    avx2: false,
  },
  {
    os: "darwin",
    arch: "arm64",
  },
  {
    os: "darwin",
    arch: "x64",
  },
  {
    os: "darwin",
    arch: "x64",
    avx2: false,
  },
  {
    os: "win32",
    arch: "arm64",
  },
  {
    os: "win32",
    arch: "x64",
  },
  {
    os: "win32",
    arch: "x64",
    avx2: false,
  },
]

const targets = singleFlag
  ? allTargets.filter((item) => {
      if (item.os !== process.platform || item.arch !== process.arch) {
        return false
      }

      if (item.avx2 === false) {
        return baselineFlag
      }

      if (item.abi !== undefined) {
        return false
      }

      return true
    })
  : allTargets

await $`rm -rf dist`

const binaries: Record<string, string> = {}
if (!skipInstall) {
  await $`bun install --os="*" --cpu="*" @opentui/core@${pkg.dependencies["@opentui/core"]}`
  await $`bun install --os="*" --cpu="*" @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`
}

// Parallel build function
async function buildTarget(item: typeof allTargets[0]) {
  const name = [
    pkg.name,
    item.os === "win32" ? "windows" : item.os,
    item.arch,
    item.avx2 === false ? "baseline" : undefined,
    item.abi === undefined ? undefined : item.abi,
  ]
    .filter(Boolean)
    .join("-")

  console.log(`building ${name}`)
  await $`mkdir -p dist/${name}/bin`

  const localPath = path.resolve(dir, "node_modules/@opentui/core/parser.worker.js")
  const rootPath = path.resolve(dir, "../../node_modules/@opentui/core/parser.worker.js")
  const parserWorker = await fs.promises.realpath(fs.existsSync(localPath) ? localPath : rootPath)
  const workerPath = "./src/cli/cmd/tui/worker.ts"

  const bunfsRoot = item.os === "win32" ? "B:/~BUN/root/" : "/$bunfs/root/"
  const workerRelativePath = path.relative(dir, parserWorker).replaceAll("\\", "/")

  await Bun.build({
    conditions: ["browser"],
    tsconfig: "./tsconfig.json",
    plugins: [solidPlugin],
    compile: {
      autoloadBunfig: false,
      autoloadDotenv: false,
      autoloadTsconfig: true,
      autoloadPackageJson: true,
      target: name.replace(pkg.name, "bun") as any,
      outfile: `dist/${name}/bin/opencode`,
      execArgv: [`--user-agent=opencode/${Script.version}`, "--use-system-ca", "--"],
      windows: {},
    },
    entrypoints: ["./src/index.ts", parserWorker, workerPath],
    define: {
      OPENCODE_VERSION: `'${Script.version}'`,
      OPENCODE_MIGRATIONS: JSON.stringify(migrations),
      OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
      OPENCODE_WORKER_PATH: workerPath,
      OPENCODE_CHANNEL: `'${Script.channel}'`,
      OPENCODE_LIBC: item.os === "linux" ? `'${item.abi ?? "glibc"}'` : "",
    },
  })

  await $`rm -rf ./dist/${name}/bin/tui`
  await Bun.file(`dist/${name}/package.json`).write(
    JSON.stringify(
      {
        name,
        version: Script.version,
        os: [item.os],
        cpu: [item.arch],
      },
      null,
      2,
    ),
  )
  return { name, version: Script.version }
}

// Parallel build execution
if (parallelFlag && targets.length > 1) {
  console.log(`Building ${targets.length} targets in parallel...`)
  const results = await Promise.all(targets.map((item) => buildTarget(item)))
  for (const result of results) {
    binaries[result.name] = result.version
  }
} else {
  for (const item of targets) {
    const result = await buildTarget(item)
    binaries[result.name] = result.version
  }
}

if (Script.release) {
  // Parallel compression
  const compressionJobs = Object.keys(binaries).map(async (key) => {
    if (key.includes("linux")) {
      await $`tar -czf ../../${key}.tar.gz *`.cwd(`dist/${key}/bin`)
    } else {
      await $`zip -r ../../${key}.zip *`.cwd(`dist/${key}/bin`)
    }
  })
  await Promise.all(compressionJobs)

  await $`gh release upload v${Script.version} ./dist/*.zip ./dist/*.tar.gz --clobber --repo ${process.env.GH_REPO}`
}

export { binaries }
